services:
  - type: web
    name: poehali-backend
    env: python
    region: frankfurt
    plan: starter
    branch: main
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEB_APP_URL
        sync: false
